name: "Integration Test"

on: [push, pull_request]

jobs:
  integration_test:
    name: "Integration Test"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ "1.15", "1.16" ]

    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin"

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STREAM_UPPER_STORAGE: "memory:///"
          STREAM_UNDER_STORAGE: "s3://test-bucket/?credential=hmac:minioadmin:minioadmin&endpoint=http:127.0.0.1:9000&location=test&force_path_style=true"
        run: make integration_test
